### ISSUE TITLE
Edit the render function

### ISSUE THREAD

**Issue by ZMY666777** [sxyu/nerfvis#12]
hello! I think this project is very useful for me to see my own model.
Now I need to use a new render function to render my scene, what should I do? should I edit the volrend and use wasm to compile it into the index.html? Or is there any easier way for me to do this?

**Comment by sxyu** [comment]
The way to modify the rendering is to through volrend's  `nerfvis_base` branch, using the emscripten build. 
This branch has been configured to build the `index.html` only. You can then copy it into this repo.

Sorry for the hacky nature of this design. This library was something I quickly made to use the volrend code for visualization and it's certainly not ideal in terms of ease of development and code quality.

**Comment by ZMY666777** [comment]
Thx
