### ISSUE TITLE
how to visualize plenoctree format?

### ISSUE THREAD

**Issue by Holmes-Alan** [sxyu/nerfvis#4]
Hello there. This is a very interesting code. I wonder if it can also visualize the plenoctree format for a 3D model. For instance, I have a tree.npy file from https://github.com/sxyu/plenoctree. How can I visualize it?

**Comment by UPstartDeveloper** [comment]
Hi @Holmes-Alan - I also think this package is super interesting. 

I wonder if what you're describing is possible via the [`scene.export()`](https://nerfvis.readthedocs.io/en/latest/nerfvis.html#nerfvis.Scene.export) method. I think you would need to at least set the `tree_file` parameter, and let `display=True` in the function call.

Just my thoughts!

**Comment by Holmes-Alan** [comment]
> Hi @Holmes-Alan - I also think this package is super interesting.
> 
> I wonder if what you're describing is possible via the [`scene.export()`](https://nerfvis.readthedocs.io/en/latest/nerfvis.html#nerfvis.Scene.export) method. I think you would need to at least set the `tree_file` parameter, and let `display=True` in the function call.
> 
> Just my thoughts!

I have a question. When we use nerfvis to display NeRF results, how do we save the generated npz file?
For instance, I have

scene.set_nerf(nerf_func, center=args.center, radius=args.radius, use_dirs=True)
scene.display(open_browser=False, port=args.port)

How do I save the scene to npz file?

**Comment by Holmes-Alan** [comment]
> > Hi @Holmes-Alan - I also think this package is super interesting.
> > I wonder if what you're describing is possible via the [`scene.export()`](https://nerfvis.readthedocs.io/en/latest/nerfvis.html#nerfvis.Scene.export) method. I think you would need to at least set the `tree_file` parameter, and let `display=True` in the function call.
> > Just my thoughts!
> 
> I have a question. When we use nerfvis to display NeRF results, how do we save the generated npz file? For instance, I have
> 
> scene.set_nerf(nerf_func, center=args.center, radius=args.radius, use_dirs=True) scene.display(open_browser=False, port=args.port)
> 
> How do I save the scene to npz file?

resolved!

**Comment by UPstartDeveloper** [comment]
^@Holmes-Alan I'm presuming the solution you found was to use `scene.export()`? [(docs)](https://nerfvis.readthedocs.io/en/latest/nerfvis.html#nerfvis.Scene.export)
