### ISSUE TITLE
How to utilize the time-slider?

### ISSUE THREAD

**Issue by ben-bou** [sxyu/nerfvis#7]
Hi,
when using NerfVis, there is a time-slider in the top-right corner, but there is nothing about it in the documentation. How can i utilize it in the visualization? Can I train a NeRF on a video and then use the time-slider to display said video from an arbitrary viewpoint?

Thanks a lot!

**Comment by sxyu** [comment]
Hi, the time slider is not designed for dynamic nerf but simply allows you to show stuff at specific times.
As seen in the documentation, any of the add* functions  support the argument `time=<int>`  which enables the times slider and it will only be shown at the specified time.
Default (-1) is to show at all times.
